### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by maxbeizer** [mattcreager/recital#1]
Is there a license for this? http://choosealicense.com/

**Comment by mattcreager** [comment]
@maxbeizer [this is all your fault](https://github.com/mattcreager/license).

**Comment by maxbeizer** [comment]
![who me?](http://www.reactiongifs.com/r/me.gif)

Bundler does [this](https://github.com/bundler/bundler/blob/26c4665788cd2601211cc54935411b8227c2f132/lib/bundler/cli/gem.rb#L90-L98) and [asks about a CoC](https://github.com/bundler/bundler/blob/26c4665788cd2601211cc54935411b8227c2f132/lib/bundler/cli/gem.rb#L90-L98).

Also, :smiley_cat:  on license
